// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAlarmActiveChange();
void onAlarmArmedChange();

bool alarmActive;
bool alarmArmed;

void initProperties(){

  ArduinoCloud.addProperty(alarmActive, READWRITE, ON_CHANGE, onAlarmActiveChange);
  ArduinoCloud.addProperty(alarmArmed, READWRITE, ON_CHANGE, onAlarmArmedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
